### ISSUE TITLE
Compatibility with Symfony 3.4 LTS - Symfony 2.8 LTS end of support for bug fixes as of November, 2018

### ISSUE THREAD

**Issue by smilearric** [ajgarlag/AjglCsvBundle#6]
Olà,

Could there be an upgrade of the ajgl/csv-bundle to make it compatible with the next LTS Symfony, version 3.4?

Indeed, the current supported version of Symfony is the 2.8 LTS version which [bug fixes support is ending](https://symfony.com/roadmap/2.8) this month: November, 2018. Security end of support is planned for next year thou.

Thanks for this great bundle. Regards,

Arric

**Comment by smilearric** [comment]
Considering a PR from https://github.com/smilearric/AjglCsvBundle, I am currently trying the following change locally for my personal use case of the CSV Bundle. My use case covers a tiny part of the bundles' features. I'm therefore not covering all use cases neither testing the bundle against the new versions contraints.

```
$ git diff
diff --git a/.travis.yml b/.travis.yml
--- a/.travis.yml
+++ b/.travis.yml
@@ -3,12 +3,13 @@ language: php
 matrix:
   fast_finish: true
   include:
-    - php: 5.4
+    - php: 5.5
       env: COMPOSER_FLAGS="--prefer-lowest"
-    - php: 5.4
     - php: 5.5
     - php: 5.6
     - php: 7
+    - php: 7.1
+    - php: 7.2
     - php: hhvm

 before_script:
@@ -17,4 +18,3 @@ script: phpunit --coverage-clover=coverage.clover
 after_script:
   - wget https://scrutinizer-ci.com/ocular.phar
   - php ocular.phar code-coverage:upload --format=php-clover coverage.clover
-
diff --git a/composer.json b/composer.json
--- a/composer.json
+++ b/composer.json
@@ -14,9 +14,9 @@
         }
     ],
     "require": {
-        "php": ">=5.4",
+        "php": ">=5.5.9",
         "ajgl/csv": "^0.4",
-        "symfony/framework-bundle": "^2.3"
+        "symfony/framework-bundle": "^2.3|^2.8|^3.4"
     },
     "require-dev": {
         "phpunit/phpunit": "^4.0"
```

For reference:

```
$ git commit
[support-symfony-3.4-lts 499bbf2] Add support for Symfony v.2.8 and v.3.4, PHP v.7.1 and v.7.2, drop support for PHP v.5.4.
 2 files changed, 5 insertions(+), 5 deletions(-)
```

**Comment by ajgarlag** [comment]
A PR will be welcome!

**Comment by smilearric** [comment]
Pull request #7 for reference "Add support for Symfony v.2.8 and v.3.4, PHP v.7.1 and v.7.2, drop support for PHP v.5.4".
